name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/cache@v2
        id: venv-cache
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if : steps.venv-cache.outputs.cache-hit != 'true'
        run : |
          poetry lock
          poetry install --no-asci
      - name: Run tests
        run: poetry run pytest